version: '3.8'

services:
  api:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env.prod
    depends_on:
      - db
    command: gunicorn --workers ${GUNICORN_WORKERS:-4} --bind 0.0.0.0:5000 "app.main:create_app()"

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-secure_password}
      - POSTGRES_DB=${POSTGRES_DB:-api_prod}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 